### ISSUE TITLE
Add option to disable blurred artwork background on the Lyrics Plus page

### ISSUE THREAD

**Issue by Yashirow** [nimsandu/spicetify-bloom#262] opened 2023-05-20 23:58 UTC
When using the Lyrics plus custom app there's an option called "colorful background" which enable/disable a background based on the album cover's color. However when using the theme there's no way to disable the option.

Option behavior without the theme :

<details>
<summary>Disabled</summary>

![image](https://github.com/nimsandu/spicetify-bloom/assets/100087778/228c8fcf-c302-401a-8c74-f7fef96a46df)
</details>

<details>
<summary>Enabled</summary>

![image](https://github.com/nimsandu/spicetify-bloom/assets/100087778/d6b3386d-ec37-4f74-adc8-bbdefc47ab50)
</details>

Option behavior with the theme :

<details>
<summary>Disabled</summary>

![image](https://github.com/nimsandu/spicetify-bloom/assets/100087778/85922052-0ba0-497d-a2d5-7329b0d650be)
</details>

<details>
<summary>Enabled</summary>

![image](https://github.com/nimsandu/spicetify-bloom/assets/100087778/ba682983-be2f-4498-bc2f-73bc78b4216f)
</details>

It could be related to the `var(--spice-main)` parameter maybe ?

**Comment by SunsetTechuila** [comment] 2023-05-21 08:10
It is not a bug, the background you see is a theme custom background, not a Lyrics Plus ones. Lyrics Plus background is hidden, so its settings have no effect

**Comment by SunsetTechuila** [comment] 2023-05-21 08:16
For now I can suggest a workaround for you:
1) Open Marketplace
2) Go to snippets
3) Press "Add CSS"
4) Paste `.lyrics-lyricsContainer-LyricsBackground { visibility: visible !important; }` to the Custom CSS field
5) Save snippet

**Comment by Yashirow** [comment] 2023-05-21 12:47
Okay thanks, it works fine.

**Comment by SunsetTechuila** [comment] 2023-06-06 14:15
@Yashirow now you need `.lyrics-lyricsContainer-LyricsBackground { display: unset !important; }`

**Comment by InsrtRandomUserHere** [comment] 2023-11-25 10:56
@SunsetTechuila Is there a new workaround for this?

**Comment by SunsetTechuila** [comment] 2023-12-11 06:19
@InsrtRandomUserHere nothing changed
if it is not working for you, try this `:root .lyrics-lyricsContainer-LyricsBackground { display: unset !important; }`
sorry for the late response

**Comment by InsrtRandomUserHere** [comment] 2023-12-12 18:26
> if it is not working for you, try this `:root .lyrics-lyricsContainer-LyricsBackground { display: unset !important; }` 

Yup, thanks that worked. Though the only problem I have now is that the scrollbar appears on the side

**Comment by nimsandu** [comment] 2024-06-25 05:22
@InsrtRandomUserHere im closing the issue! open an issue anytime if anything goes wrong! until we meet again, keep blooming ^_~

**Closed by nimsandu** 2024-06-25 05:22 UTC
Labels: enhancement
