### ISSUE TITLE
Song cover doesn't appear

### ISSUE THREAD

**Issue by ggato1** [nimsandu/spicetify-bloom#277] opened 2023-06-14 02:24 UTC
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Installed from: Spotify site
- Spicetify version: v2.20.0
- Color scheme: dark
- Extensions: adblock, full screen
- Custom apps: none
- Bloom installation method: Spicetify Marketplace
```

### Description

When Spotify starts or when reloading, the song cover that should be next to the song title in the lower left appears in its place for half a second, then in another half second it appears in the right and then disappears.

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/102178415/ae945f80-c9b2-4338-bb14-8fffc1be2c3b)
here its on the right after a short moment where it is on its place 

![image](https://github.com/nimsandu/spicetify-bloom/assets/102178415/f37905cf-2cb3-4df3-8b75-64aa4cb97f60)
how it stays after starting

**Comment by SunsetTechuila** [comment] 2023-06-14 03:28
yeah, known issue caused by the right sidebar

**Comment by SunsetTechuila** [comment] 2023-06-14 03:30
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/ef5bd3a0-dc6d-454f-afc2-52869549a3b5)
btw enable hardware acceleration in the app settings

**Comment by ggato1** [comment] 2023-06-16 01:45
> ![image](https://user-images.githubusercontent.com/115353812/245666976-ef5bd3a0-dc6d-454f-afc2-52869549a3b5.png) btw enable hardware acceleration in the app settings

oh ok i'll do that

**Comment by SunsetTechuila** [comment] 2023-06-19 09:40
@ggato1 open the experimanal features, disable `Enable the view on the right sidebar`, minimize cover art then the enable right sidebar

**Comment by ggato1** [comment] 2023-06-21 01:10
> @ggato1 open experimanal features, uncheck `Enable the view on the right sidebar`, minimize cover art, then enable the right sidebar

That worked! Thank you

**Comment by SunsetTechuila** [comment] 2023-06-21 09:21
I will leave this issue open until I find a way to make the problem not appear at all, or until I realize that this is impossible to do

**Comment by SunsetTechuila** [comment] 2023-11-11 20:00
closing this because since spotify v1.2.24 the right sidebar cannot be turned off

**Closed by SunsetTechuila** 2023-11-11 20:00 UTC
Labels: bug, good first issue
