### ISSUE TITLE
Interface problem with some Lyrics plus features

### ISSUE THREAD

**Issue by Yashirow** [nimsandu/spicetify-bloom#165] opened 2023-02-18 00:17 UTC
*2 issues in two days sorry for making you work !*

Basically the "unsynced" category comes out of the dropdown menu when using some lyrics plus features :

Normal behavior :
![image](https://user-images.githubusercontent.com/100087778/219819045-bbd3143c-7e48-444e-9cce-449841709c8c.png)

When using the conversion feature :
![image](https://user-images.githubusercontent.com/100087778/219819440-729b409d-166e-4832-be8c-f9a13f49f94e.png)

When using the compact feature :
![image](https://user-images.githubusercontent.com/100087778/219819469-b440ea26-8c23-409a-8b16-f82603c4ace7.png)

**Comment by nimsandu** [comment] 2023-02-19 03:11
@Yashirow It's your theme. So you must report anything no matter what. So don't worry.
Well that strange problem is something I personally tried to solve and still couldn't.
So let me try some other ways too

**Comment by SunsetTechuila** [comment] 2023-02-24 13:30
@nimsandu all we can do about that - resore default Lyrics Plus display style:
![image](https://user-images.githubusercontent.com/115353812/221184725-44e68bfe-4e78-4d22-9a54-c1bce2d98dad.png)
The issue is in Lyrics Plus logic and rendering algorithms 
If you want I can make a commit restoring default  Lyrics Plus display style

**Comment by nimsandu** [comment] 2023-02-24 13:34
> @nimsandu all we can do about that - resore default Lyrics Plus display style:
> 
> ![image](https://user-images.githubusercontent.com/115353812/221184725-44e68bfe-4e78-4d22-9a54-c1bce2d98dad.png)
> 
> The issue is in Lyrics Plus logic and rendering algorithms 
> 
> If you want I can make a commit restoring default  Lyrics Plus display style

It's fine cuz our main focus is to reduce user confusions 

@SunsetTechuila I really appreciate everything you do.
So you are welcome to make the commit ill look into all of your prs asap.

**Comment by nimsandu** [comment] 2023-02-26 18:33
@Yashirow this issue has been fixed with the merge of #191 by @SunsetTechuila

**Closed by nimsandu** 2023-02-26 18:33 UTC
