### ISSUE TITLE
Issues + request

### ISSUE THREAD

**Issue by stpnwf** [nimsandu/spicetify-bloom#220] opened 2023-03-28 21:29 UTC
These issues can be reproduced on a brand new installation of Spotify + Spicetify + Marketplace with just Bloom installed from the Marketplace. 
Still loving this Spotify theme. Thanks for it!

## Issues:

<details>
    <summary>1. Play and Pause buttons are overlayed onto themselves.</summary>
<img src="https://user-images.githubusercontent.com/81482539/228357601-1652ba9c-cb30-4422-80ee-5d923ccd97b8.png" width="480">
<img src="https://user-images.githubusercontent.com/81482539/228369643-3932c7ea-1f01-406a-8388-f794c32c1ef8.png" width="450">
</details>

<details>
    <summary>2. Some elements have the same color no matter the color scheme. Nothing in color.ini will affect them </summary>
<img src="https://user-images.githubusercontent.com/81482539/228358473-09f638e6-1257-4cf5-8193-ddf7973b4d62.png" width="480">
<img src="https://user-images.githubusercontent.com/81482539/228358604-1eea8442-9bc8-4d59-b994-0242021db6e1.png" width="420">
<img src="https://user-images.githubusercontent.com/81482539/228579498-667ea212-549a-462e-b88d-30a09aea08c3.png" width="505">
<img src="https://user-images.githubusercontent.com/81482539/229672348-00264e45-9dbc-4d7a-be3a-890e963d7108.png" width="730">
<img src="https://user-images.githubusercontent.com/81482539/228359600-541da45a-9660-49a8-9401-9d7b78b3412e.png" width="700">

</details>

<details>
    <summary>3. Minor issue: there is no blur when clicking the user menu, unlike other dialogs</summary>
<img src="https://user-images.githubusercontent.com/81482539/228360686-133f6474-0a1e-4766-b7c0-af76cd9f4df9.png" width="280">
</details>

<details>
    <summary>4. Play bar obstructs what Friends are playing as well as Lyrics</summary>
<img src="https://user-images.githubusercontent.com/81482539/228362148-5b6c2034-fa28-461e-b80b-6c8b64063765.png" width="535">
<img src="https://user-images.githubusercontent.com/81482539/228362417-85bc595f-30f1-4964-b8c5-a1ba459e269e.png" width="690">
</details>

<details>
    <summary>5. Weird glitch when scrolling through sidebar playlists</summary>

It scrolls fine until it gets about halfway through, then that happens...

<video src="https://user-images.githubusercontent.com/81482539/228363003-3da686f0-de56-48ea-8b0c-77a4849c35c5.webm" width="345">
[Screencast from 2023-03-28 18-03-48.webm](https://user-images.githubusercontent.com/81482539/228366728-90c559f7-e386-4039-abc4-27ccb1995e90.webm)
</details>

<details>
    <summary>6. Liked Songs + Your Episode + New Play list buttons won't remain hidden once Spotify is restarted.</summary>
<video src="https://user-images.githubusercontent.com/81482539/228366728-90c559f7-e386-4039-abc4-27ccb1995e90.webm" width="280">
</details>

## Request

<details>
    <summary>1.  Any chance we could get support for custom images to be displayed instead of the folders? Ideally like Dribbblish, but anything similar really. Personally I am not a fan of how they look, and they even look broken on some dark color schemes... like Comfy and Dark Mono</summary>

<img src="https://user-images.githubusercontent.com/81482539/228364157-2a1f6271-a00d-480f-823e-371e300abf93.png" width="220">
</details>

**Comment by nimsandu** [comment] 2023-04-01 07:51
@stpnwf thanks for reaching out and providing a well-organized issue. we will do our best to resolve these issues in the near future

**Comment by SunsetTechuila** [comment] 2023-04-06 14:35
> 3. Minor issue: there is no blur when clicking the user menu, unlike other dialogs

Can't reproduce

**Comment by stpnwf** [comment] 2023-04-07 02:59
> Can't reproduce

I am on Linux, maybe that is it. Tried it on both Fedora 37 and Vanilla OS with Bloom from the marketplace and Spotify installed via Flathub.

Although some of those issues may not be relevant anymore given Spotify's redesign. Unsure if it will influence Bloom's interface going forward.

**Comment by SunsetTechuila** [comment] 2023-04-07 05:05
3 is definitely a spicetify issue, not a theme

**Comment by Raiden0456** [comment] 2023-05-09 20:35
> > Can't reproduce
> 
> I am on Linux, maybe that is it. Tried it on both Fedora 37 and Vanilla OS with Bloom from the marketplace and Spotify installed via Flathub.
> 
> Although some of those issues may not be relevant anymore given Spotify's redesign. Unsure if it will influence Bloom's interface going forward.

Same here, pause and play buttons overlay each other, this is definitely a linux problem, as i'm running fedora 38 + GNOME

**Comment by windowz414** [comment] 2023-05-10 08:38
> > > Can't reproduce
> > 
> > 
> > I am on Linux, maybe that is it. Tried it on both Fedora 37 and Vanilla OS with Bloom from the marketplace and Spotify installed via Flathub.
> > Although some of those issues may not be relevant anymore given Spotify's redesign. Unsure if it will influence Bloom's interface going forward.
> 
> Same here, pause and play buttons overlay each other, this is definitely a linux problem, as i'm running fedora 38 + GNOME

Try updating Spicetify and Bloom now. That issue is resolved.

Tested environments: ChromeOS Linux Development Environment (Debian Bullseye), EndeavourOS GNOME, ZorinOS 16.2

**Comment by SunsetTechuila** [comment] 2023-05-13 07:24
> 4. Play bar obstructs what Friends are playing as well as Lyrics

fixed in https://github.com/nimsandu/spicetify-bloom/commit/be77059df1c1bfe5f5d7ae0c6ecbdc08c15ebcc2

**Comment by SunsetTechuila** [comment] 2023-05-13 07:26
> 5. Weird glitch when scrolling through sidebar playlists

Fixed in https://github.com/nimsandu/spicetify-bloom/commit/a4ef0b5fc14ba19360624ece033c581efe442014

**Comment by SunsetTechuila** [comment] 2023-05-13 07:30
> 2. Some elements have the same color no matter the color scheme. Nothing in color.ini will affect them

`and more` can't be fixed:
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/43b239cf-0ebe-4705-9433-13c2b1424ba2)

**Comment by SunsetTechuila** [comment] 2023-05-13 07:40
> 2. Some elements have the same color no matter the color scheme. Nothing in color.ini will affect them

fixed completely in https://github.com/nimsandu/spicetify-bloom/commit/47bb62196dbc5a20358f13f772da72204628b51f

**Comment by SunsetTechuila** [comment] 2023-05-13 07:43
@stpnwf so all issues are fixed now?

nice color scheme you have btw, do you want to make pr with it?

**Comment by SunsetTechuila** [comment] 2023-05-19 12:29
> Any chance we could get support for custom images to be displayed instead of the folders? Ideally like Dribbblish

added in https://github.com/nimsandu/spicetify-bloom/commit/a3b751bd4732f7a1df05d43a67ee671a9961a181
@stpnwf are we ready to close the issue?

**Comment by SunsetTechuila** [comment] 2023-05-19 18:28
> > Minor issue: there is no blur when clicking the user menu, unlike other dialogs

> Can't reproduce

Still can't, but I now I know the reason. As karimawii has in #259 you have a menu appears right after user-widget box element, not at the very end of the body. Karimavi, as I see, has no blur either, which confirms my theory.

For the same reason, for example, this menu does not have transparency:
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/53b6254e-a4cb-4c91-b987-93e7ddc7d4dc)
And this is what happens if we move it to the end of the body:
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/b597f4c6-f89a-4d53-acf3-ef0bcab525eb)
Backdrop filters is working!

I don't know how to fix this right now.

**Comment by SunsetTechuila** [comment] 2023-05-19 19:50
[fixed](9936025c8d50cd9f6bdc6c48e8c845c9ee97c974)
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/79962abf-4853-4f34-9d9e-697b62b77afa)

**Comment by SunsetTechuila** [comment] 2023-05-19 20:29
@stpnwf are we ready to close the issue?
nice green color scheme you have btw, do you want to make pr with it?

**Comment by stpnwf** [comment] 2023-05-19 22:18
I won't be able to check it until hopefully this weekend, but I will close this issue and open another if there are still issues.
Do you have any idea when the updated version will hit Marketplace?

>nice green color scheme you have btw, do you want to make pr with it?
 
Thanks, it is heavily inspired by the Zorin OS Dark Green color scheme. I really love it.
If you'd like I can make a PR, but I have never made one before, so I'd have to look up how to do it. LMK
These are the colors though:

```
text=BBF1DD
subtext=6b8a7f
alt-text=6b8a7f
main=1B2421
sidebar=1B2421
player=101411
player-border=33433d
player-bar-shadow=BBF1DD
player-bar-bg=323336
card=101411
shadow=101411
selected-row=33433D
button=28c48b
button-active=00ac6f
button-disabled=33433D
tab-active=33433D
notification=6b8a7f
notification-error=d43353
misc=6b8a7f
not-selected=6b8a7f
accent=BBF1DD
layer-shadow=1B2421
contour=1B2421
```

**Sadly, I don't have a screenshot for it ATM bc I am playing around with a frankeinstein theme rn (in the pic below), but the pic below should have the same feel as the above color scheme.** 

![Screenshot from 2023-05-19 19-07-29-obfuscated](https://github.com/nimsandu/spicetify-bloom/assets/81482539/b70837f4-1e8e-48ae-bee9-317e6f15c405)

**Comment by SunsetTechuila** [comment] 2023-05-19 22:24
> Do you have any idea when the updated version will hit Marketplace?

Usually it takes two days

> If you'd like

Personally I definitely would

**Comment by SunsetTechuila** [comment] 2023-05-19 22:28
> but I will close this issue and open another if there are still issues.

It's better not to close current issue until you are sure that all is fixed than to close and open a new one

**Comment by stpnwf** [comment] 2023-05-19 23:00
>Usually it takes two days

Awesome, then I will check that and file the request on Sunday.

>It's better not to close current issue until you are sure that all is fixed than to close and open a new one

Alright, thanks for reopening it.

**Comment by stpnwf** [comment] 2023-06-01 15:55
> @stpnwf hello, just a quick reminder

Sorry, I forgot.

Most issues were fixed but I still encountered some:

![Screenshot from 2023-06-01 15-54-46](https://github.com/nimsandu/spicetify-bloom/assets/81482539/585bf0e8-d949-43ff-93cd-ad2552b84c4c)

![Screenshot from 2023-06-01 15-49-57](https://github.com/nimsandu/spicetify-bloom/assets/81482539/8236e49e-152f-4994-814a-0d4482914c60)

**Comment by windowz414** [comment] 2023-06-01 17:10
> > pic 3
> 
> what's wrong?

@SunsetTechuila look at queue button

**Comment by SunsetTechuila** [comment] 2023-06-01 17:14
Thanks. I'll probably make **all** the buttons spice-text color

**Comment by stpnwf** [comment] 2023-06-02 01:56
> I'm waiting for the color scheme first of all)

I am having issues with SSH, will try pushing it once I get it working.

**Comment by stpnwf** [comment] 2023-06-02 22:15
> I'm waiting for the color scheme first of all)

[Here you go!](https://github.com/nimsandu/spicetify-bloom/pull/271)

**Comment by kernelb00t** [comment] 2023-12-29 11:18
@stpnwf Are there still any issues?

**Closed** 2024-06-25 05:17 UTC
Labels: bug, enhancement

**Comment by nimsandu** [comment] 2024-06-25 05:19
@stpnwf i closed this as this is inactive, be comfortable to reopen anytime if needed! thanks!
