### ISSUE TITLE
The sound icon appears over the liked sounds icon

### ISSUE THREAD

**Issue by GastonKhouri** [nimsandu/spicetify-bloom#130] opened 2022-11-27 18:33 UTC
The sound icon appears on top of the liked sounds icon.

To reproduce the error, just play a song in the liked sounds list.

![image](https://user-images.githubusercontent.com/68894611/204153231-347275c0-a646-421d-8d5c-8050f0a46cec.png)

**Comment by windowz414** [comment] 2022-11-28 03:09
*What in tarnation*

**Comment by nimsandu** [comment] 2022-11-28 03:47
Well @GastonKhouri it suppose to be a now playing liked songs playlist (when you click it song will pause) (its a functionality not a bug)but we will replace that volume icon with a pause icon in near future
And thank you for reaching out bloom-community

**Comment by nimsandu** [comment] 2023-04-10 12:42
fixed by @SunsetTechuila

**Closed** 2023-04-10 12:41 UTC
