### ISSUE TITLE
Play / Pause Button Doesn't in Correct Position

### ISSUE THREAD

**Issue by Aseem-ibn-imthiyas** [nimsandu/spicetify-bloom#368] opened 2024-09-06 22:50 UTC
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.45.454.gc16ec9f6
- Installed from: Spotify site
- Spicetify version: Spicetify v2.37.7
- Color scheme: Dark
- Extensions: Shuffle+ , FullScreen , Adblockify
- Custom apps: Lyricsplus
- Bloom installation method: Spicetify Marketplace
```

### Description

after installed this theme Play Button Position is changed 

only problem is playbuttonn

please change it correct position ASAP

### Screenshots

![image_2024-09-07_041412341](https://github.com/user-attachments/assets/67057255-34a5-4cf0-bb32-3c9066680ac0)

**Comment by mekwall** [comment] 2024-09-07 21:59
Duplicate of https://github.com/nimsandu/spicetify-bloom/issues/365

**Closed** 2024-09-09 18:13 UTC
Labels: bug

**Comment by Aseem-ibn-imthiyas** [comment] 2024-09-12 03:50
Thanks ❤️
