### ISSUE TITLE
Weird bar

### ISSUE THREAD

**Issue by teddythinh** [nimsandu/spicetify-bloom#281] opened 2023-06-23 10:07 UTC
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different
- [X] I have problem with a theme custom feature

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (32 bit) 1.2.13.661.ga588f749
- Installed from: Spotify site
- Spicetify version: v2.20.1
- Color scheme: Bloom/dark/light
- Extensions:
- Custom apps:
- Bloom installation method: PowerShell script
```

### Description

I have a strange bar on top of the Spotify app. When I scroll, it follows. It appears in all 3 themes.

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/85171754/25572771-a7f0-4221-a187-4abd69de6459)

![image](https://github.com/nimsandu/spicetify-bloom/assets/85171754/9b04230a-3cd9-48d8-a354-b97952ac5df6)

**Comment by SunsetTechuila** [comment] 2023-06-23 10:15
duplicate of #278

**Closed by SunsetTechuila** 2023-06-23 10:15 UTC
Labels: bug

**Comment by SunsetTechuila** [comment] 2023-06-23 10:16
duplicate of #280

**Comment by SunsetTechuila** [comment] 2023-06-23 10:20
you need [1.2.14](https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.14.1149.ga3ae422d-1027.exe) (forced Library X)

**Comment by teddythinh** [comment] 2023-06-23 10:25
@SunsetTechuila thank you, it's not getting bug anymore
