### ISSUE TITLE
Some enhancements are needed to the sidebar

### ISSUE THREAD

**Issue by D4rckeyy** [nimsandu/spicetify-bloom#150] opened 2023-02-03 01:38 UTC
![image](https://user-images.githubusercontent.com/124324009/216490640-551342cd-7aa3-4b51-9e29-0012b45cbe84.png)

**Comment by nimsandu** [comment] 2023-02-04 03:21
could you please mention your spicetify and spotify versions

**Comment by nimsandu** [comment] 2023-02-04 03:32
Spotify for Windows
1.2.4.912.g949d5fd0
Spicetify v2.16.1

can reproduce the issue on my end with above configurations.
we will try to fix that. @D4rckeyy thanks

**Comment by D4rckeyy** [comment] 2023-02-04 05:23
Spotify for Windows
1.2.4.912.g949d5fd0
Spicetify v2.16.1

> could you please mention your spicetify and spotify versions

**Comment by nimsandu** [comment] 2023-02-04 06:57
@D4rckeyy thanks
it precisely matches with mine
I'll try figure out what happened.

**Comment by Asyx3** [comment] 2023-02-05 09:57
Hey, I'm having the same issue. Using the same version of Spotify and Spicetify as D4rckeyy. Cheers

**Comment by nimsandu** [comment] 2023-02-07 07:13
@Asyx3 even i have this issue btw
![image](https://user-images.githubusercontent.com/57834844/217173341-077b1460-8e2d-4b2e-aac2-ae89d52f22a7.png)
I'm trying my best to fix it.

**Comment by clout2k** [comment] 2023-02-08 08:55
![image](https://user-images.githubusercontent.com/75420281/217481757-77889474-69bd-48c8-a171-b04194faaf38.png)
through trial and error here's my work around, I removed the whole ` waitForElement([".main-rootlist-rootlistItem"], function () {` function and replaced it with the one below. Its a little buggy as in some playlist on the left side are missing and when u click on a playlist that's in the middle of the list it resets the scroll position.  also needs css work but i hope this works and let me know if u find a better solution!

    const cache = new Map();
    async function fetchPlaylistData(url) {
    const response = await Spicetify.CosmosAsync.get(url);
    const { items, next } = response;
    return [...items, ...(next ? await fetchPlaylistData(next) : [])];
    } 

    async function addPlaylistIcons() {
    while (!Spicetify || !Spicetify.Platform || !Spicetify.CosmosAsync) {
      await new Promise((resolve) => setTimeout(resolve, 100));
    }

    const playlistList = await new Promise((resolve) => {
      const interval = setInterval(() => {
        const element = document.querySelector("#spicetify-playlist-list");
        if (element) {
          clearInterval(interval);
          resolve(element);
        }
      }, 100);
    });
    const playlistData = await fetchPlaylistData("https://api.spotify.com/v1/me/playlists?limit=50");
    const observer = new MutationObserver(async () => {
      observer.disconnect();
      await updatePlaylistList(playlistData);
      observer.observe(playlistList, { childList: true, subtree: true });
    });

    await updatePlaylistList(playlistData);
    observer.observe(playlistList, { childList: true, subtree: true });
    }

    async function updatePlaylistList(playlistData) {
    const playlistElements = await new Promise((resolve) => {
      const interval = setInterval(() => {
        const elements = document.querySelectorAll("#spicetify-playlist-list li a");
        if (elements.length > 0) {
          clearInterval(interval);
          resolve(Array.from(elements));
        }
      }, 100);
    });

    for (const element of playlistElements) {
      const [id] = element.href.split("/").slice(-1);
      const [type] = element.href.split("/").slice(-2, -1);
      let icon = cache.get(id);
      if (!icon) {
        switch (type) {
          case "playlist":
            const playlist = playlistData.find((p) => p.id === id);
            const image = playlist ? playlist.images[0] || {} : {};
            icon = {
              src: image.url,
              size: "72px",
            };
            cache.set(id, icon);
            break;
          case "folder":
            icon = {
              src: "https://cdn.jsdelivr.net/gh/nimsandu/spicetify-bloom@master/assets/fluentui-system-icons/ic_fluent_folder_24_filled.svg",
              size: "72px",
            };
            cache.set(id, icon);
            break;
        }
      }

      if (icon.src) {
        element.style.backgroundImage = `url('${icon.src}')`;
        element.style.backgroundRepeat = "no-repeat";
        element.style.backgroundSize = `${icon.size}`;
        element.style.backgroundPosition = "center";
      }
    }
    }
    addPlaylistIcons();

**Comment by nimsandu** [comment] 2023-02-08 08:58
@clout2k Wow great work!
Ill test this out and try to improve it. If you can make this better, please open a pr
Thanks

**Comment by nimsandu** [comment] 2023-02-10 02:59
@D4rckeyy @Asyx3 its being patched thanks to @clout2k and now it looks like this
![image](https://user-images.githubusercontent.com/57834844/217989101-d5b43c5b-787a-4f28-a2f2-113cad43864f.png)
all the credit goes to @clout2k 
imma leave this open with a different title because it still needs some enhancements.

**Comment by nimsandu** [comment] 2023-02-10 03:24
@Asyx3 @D4rckeyy  conform the fix by installing latest bloom.

**Comment by nimsandu** [comment] 2023-04-11 14:52
closing the issue as completed
@clout2k thanks

**Closed by nimsandu** 2023-04-11 14:52 UTC
