### ISSUE TITLE
"Download" button shows as clickable without spotify premium

### ISSUE THREAD

**Issue by Insane-Owl** [nimsandu/spicetify-bloom#261] opened 2023-05-20 20:22 UTC
The "Download" buttons in the right-click menu, and at the top of playlists should only be there if the user has Spotify Premium, but they show for free users too (they have no functionality).

![2023-05-20 12276 Spotify](https://github.com/nimsandu/spicetify-bloom/assets/78328941/4f15b907-1d36-474e-b65b-732dd7b74431)
![2023-05-20 55760 Spotify](https://github.com/nimsandu/spicetify-bloom/assets/78328941/3f9b00ac-046f-4041-82d8-c046b9393eb5)

**Comment by SunsetTechuila** [comment] 2023-05-20 20:47
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/21c1f8ff-c8f5-4539-b4c2-a457d82dc0ed)
not a bug, but the style needs to be rectified

**Comment by SunsetTechuila** [comment] 2023-05-20 20:50
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/431be3ca-074e-4d88-a804-13f11dcaaa5f)
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/84330da7-8899-4346-b3a8-97d9593caba1)

and here the style is completely identical to the stock ones

**Comment by Insane-Owl** [comment] 2023-05-20 20:59
Oh, I guess the playlist button is how it is in stock.

IMO it should be gone either way if the User doesn't have premium.

**Comment by SunsetTechuila** [comment] 2023-05-20 21:03
> IMO it should be gone either way if the User doesn't have premium.

agree, but this needs to be implemented as a separate extension

**Comment by SunsetTechuila** [comment] 2023-05-21 08:33
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/c2f51794-288e-456d-9bb3-12fab18ac896)

@Insane-Owl are we ready to close the issue?

**Closed** 2023-05-21 13:20 UTC
Labels: enhancement
