### ISSUE TITLE
The search bar unfocuses itself after typing for some time

### ISSUE THREAD

**Issue by X1nto** [nimsandu/spicetify-bloom#332] opened 2024-03-09 04:58 UTC
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.32.997.g4c6498b6
- Installed from: Spotify site
- Spicetify version: 2.33.2
- Color scheme: dark
- Extensions: Volume Profiles
- Custom apps: N/A
- Bloom installation method: Spicetify Marketplace
```

### Description

The search bar unfocuses itself a few seconds after I start typing.

1. Go to Search
2. Start searching for a song
3. After typing for some time (the interval is random, which could range from 0.5s to 3s) the search bar unfocuses itself, forcing me to manually click on it again to continue entering text.

### Screenshots

https://github.com/nimsandu/spicetify-bloom/assets/48173186/1936f328-d97d-4822-9c15-650296f72275

**Comment by windowz414** [comment] 2024-03-09 07:53
Bloom is kinda outdated and @nimsandu doesn't seem to be available just yet. This bug is possibly because Spotify or Spicetify updated some stuff on their end which we have to adapt Bloom to, but sadly I'm not that knowledgeable myself. It's better to wait for him to have some spare time to fix this bug.

--
Thanks for trying out Bloom and the bug report, Keep Blooming!

**Comment by X1nto** [comment] 2024-03-09 09:43
Thank you for replying. I'll see if I can PR a fix in the meantime.

**Comment by windowz414** [comment] 2024-03-09 10:46
Any time, a PR would be much appreciated!

**Comment by k3n4i70** [comment] 2024-03-27 13:20
still nothing?

**Comment by stel-bl** [comment] 2024-03-27 14:34
Unfortunately no, I don't think we've received a PR just yet. At least I didn't get a notification for it.

**Comment by notgabry** [comment] 2024-03-28 22:22
i'm working on a pr

**Comment by kernelb00t** [comment] 2024-04-01 10:17
@notgabry Can confirm removing this line fixes the issue, version `latest of the latest`.
Can you make a draft pr? So we can track possible regressions.

**Comment by notgabry** [comment] 2024-04-04 06:04
I'm gonna work on it later today

**Comment by stel-bl** [comment] 2024-04-04 06:22
Thank you so much! Eagerly waiting for your PR!

**Comment by notgabry** [comment] 2024-04-09 16:27
a little late but i made the pr

**Comment by aurelbdx** [comment] 2024-05-20 10:02
Hello, I still have this problem, it is not fixed yet?

**Comment by aurelbdx** [comment] 2024-05-20 10:11
Hello, I still have this problem, it is not fixed yet?

**Comment by nimsandu** [comment] 2024-06-25 07:59
the issue is now fixed

**Closed by nimsandu** 2024-06-25 07:59 UTC
Labels: bug
