### ISSUE TITLE
Sidebar Icons are stretched, and There is a large strip across the top of the window

### ISSUE THREAD

**Issue by Insane-Owl** [nimsandu/spicetify-bloom#286] opened 2023-06-26 18:19 UTC
### Did you read the README?

- [ ] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [ ] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [ ] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different
- [ ] I have problem with a theme custom feature

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Installed from: Spotify site
- Spicetify version: 2.20.2
- Color scheme: All
- Extensions: Adblock
- Custom apps: None
- Bloom installation method: Spicetify Marketplace
```

### Description

Sidebar Icons are stretched, and There is a large strip across the top of the window

### Screenshots

![Screenshot 2023-06-26 135402](https://github.com/nimsandu/spicetify-bloom/assets/78328941/84bb0843-5645-4e03-b54d-878c498baefd)
![Screenshot 2023-06-26 135654](https://github.com/nimsandu/spicetify-bloom/assets/78328941/20a76188-941a-48a8-9aca-4d28134b5738)

**Comment by SunsetTechuila** [comment] 2023-06-26 18:21
Duplicate of #280

**Closed by SunsetTechuila** 2023-06-26 18:21 UTC
Labels: bug
